server:
  port: 8123
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pickle_pictures
    username: root
    password: 123456abc

#   batis is the frame for doing database operations
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # print the batis log when dev
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  it means doing the logic delete when delete value is 1
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: apiOfficialDocs
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.legion.picturebackend.controller
